export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';


export const LOG_IN = 'LOG_IN';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';


export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const NEW_PASSWORD = 'NEW_PASSWORD';
export const EDIT_PASSWORD = 'EDIT_PASSWORD';

export const EDIT_PROFILE = 'EDIT_PROFILE';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';

export const ADD_IDEA = 'ADD_IDEA';
export const ADD_IDEA_SUCCESS = 'ADD_IDEA_SUCCESS';
export const ADD_IDEA_FAILURE = 'ADD_IDEA_FAILURE';

export const UPDATE_IDEA = 'UPDATE_IDEA';

export const LOAD_IDEA = 'LOAD_IDEA';
export const LOAD_IDEA_SUCCESS = 'LOAD_IDEA_SUCCESS';
export const LOAD_IDEA_FAILURE = 'LOAD_IDEA_FAILURE';

export const FETCH_IDEA = 'FETCH_IDEA'

export const EDIT_IDEA = 'EDIT_POST';
export const EDIT_IDEA_SUCCESS = 'EDIT_IDEA_SUCCESS';
export const EDIT_IDEA_FAILURE = 'EDIT_IDEA_FAILURE';

export const DELETE_IDEA = 'DELETE_IDEA';
export const DELETE_IDEA_SUCCESS = 'DELETE_IDEA_SUCCESS';
export const DELETE_IDEA_FAILURE = 'DELETE_IDEA_FAILURE';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

export const SHOW_LOADING_BAR = 'SHOW_LOADING_BAR'
export const HIDE_LOADING_BAR = 'HIDE_LOADING_BAR'

export const LOAD_ONE_IDEA = 'LOAD_ONE_IDEA';
export const LOAD_ONE_IDEA_SUCCESS = 'LOAD_ONE_IDEA_SUCCESS';
export const LOAD_ONE_IDEA_FAILURE = 'LOAD_ONE_IDEA_FAILURE';

export const LOAD_ALL_IDEAS = 'LOAD_ALL_IDEAS';
export const LOAD_IDEAS_SUCCESS= 'LOAD_IDEAS_SUCCESS';
